### ISSUE TITLE
Design Elements

### ISSUE THREAD

**Issue by holly-johnson** [KayleeZnamenacek/BlackMarketClothingExchange#11]
Are there additional brand elements you could find creative ways to use within the site? Have you worked on the pattern and thought of elements you could use or create from it?

**Comment by emmaschaible** [comment]
Experimented with this and tried using some of the clothing in the image in the hero and unfortunately it did not look as I thought it would. Was a bit distracting.

**Comment by KayleeZnamenacek** [comment]
As long as our final push goes well, there should be a use of rules within the content. It's hard to go off a brand that has no branding if that makes sense.
