### ISSUE TITLE
Use of grid-container

### ISSUE THREAD

**Issue by holly-johnson** [KayleeZnamenacek/BlackMarketClothingExchange#6]
User grid-container on the outer most tag of your band. If you need the background color to go full with, add the additional class of "full" on the tag. Then you can override grid-container to increase space between sections holistically and not have unnecessary code written.

**Comment by KayleeZnamenacek** [comment]
I started working on this. Tried adding an additional class of full on the background color with grid-container but it broke the grid-container.
